# Generated by Django 2.1.7 on 2019-04-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Test',
        ),
    ]
