# Generated by Django 2.1.7 on 2019-04-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190406_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trashpoint',
            old_name='user_id',
            new_name='user',
        ),
    ]
