# Generated by Django 2.1.7 on 2019-04-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190406_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashpoint',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
