# Generated by Django 2.1.7 on 2019-04-06 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_event_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trashpoint',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Event'),
        ),
    ]
