# Generated by Django 2.1.7 on 2019-04-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20190406_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='total_persons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
