# Generated by Django 2.2 on 2019-04-07 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_event_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='user_id',
            new_name='user',
        ),
    ]
