# Generated by Django 2.2 on 2019-04-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190407_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='role',
            field=models.CharField(choices=[('Volunteer', 'Volunteer'), ('Collector', 'Collector'), ('Admin', 'Admin'), ('Info', 'Info')], max_length=50),
        ),
    ]
